In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("dataset/cars93.csv")

In [3]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [4]:
data.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [6]:
data.shape

(93, 10)

info() : gives all data information like shape,null values,clumns rows etc

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     str
 1   Model           93 non-null     str
 2   Type            93 non-null     str
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     str
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), str(4)
memory usage: 7.4 KB

In [8]:
data['Manufacturer'].unique()

<StringArray>
[        'Acura',          'Audi',           'BMW',         'Buick',
      'Cadillac',     'Chevrolet',      'Chrylser',      'Chrysler',
         'Dodge',         'Eagle',          'Ford',           'Geo',
         'Honda',       'Hyundai',      'Infiniti',         'Lexus',
       'Lincoln',         'Mazda', 'Mercedes-Benz',       'Mercury',
    'Mitsubishi',        'Nissan',    'Oldsmobile',      'Plymouth',
       'Pontiac',          'Saab',        'Saturn',        'Subaru',
        'Suzuki',        'Toyota',    'Volkswagen',         'Volvo']
Length: 32, dtype: str

In [9]:
data['Manufacturer'].nunique()

32

In [10]:
data['Type'].value_counts()

Type
Midsize    22
Small      21
Compact    16
Sporty     14
Large      11
Van         9
Name: count, dtype: int64

In [11]:
data.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

to fill nan (null)values.

In [14]:
data['AirBags'].unique()

<StringArray>
['Driver only', 'Driver & Passenger', nan]
Length: 3, dtype: str

In [15]:
data['AirBags'].mode()

0    Driver only
Name: AirBags, dtype: str

In [24]:
#data.loc[data['AirBags'].isna()==True,'AirBags'] = "Driver only"
data['AirBags'].fillna("Driver only")
data

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [27]:
res = data['AirBags'].mode()
res

0    Driver only
Name: AirBags, dtype: str

In [29]:
data['AirBags'].fillna(res[0])

0            Driver only
1     Driver & Passenger
2            Driver only
3     Driver & Passenger
4            Driver only
             ...
88    Driver & Passenger
89    Driver & Passenger
90    Driver & Passenger
91           Driver only
92    Driver & Passenger
Name: AirBags, Length: 93, dtype: str

In [30]:
data.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags            0
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [31]:
data['Luggage.room'].unique()

array([11., 15., 14., 17., 13., 16., 21., 18., nan, 20., 12., 10.,  8.,
        9., 19., 22.,  6.])

In [34]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [35]:
data

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [36]:
data['Luggage.room'].mean()

np.float64(13.890243902439025)

In [42]:
data['Luggage.room'].unique()

array([11., 15., 14., 17., 13., 16., 21., 18., nan, 20., 12., 10.,  8.,
        9., 19., 22.,  6.])

In [43]:
data['Luggage.room'].mode()

0    14.0
Name: Luggage.room, dtype: float64

In [60]:
#data.loc[data['Luggage.room'].isna()==True,'Luggage.room'] = 13.8
data['Luggage.room'].fillna(13.8)
data

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,13.8
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [59]:
data.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    2
Luggage.room      0
dtype: int64

In [63]:
data1=data.dropna()
data1

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,13.8
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [64]:
data1.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [65]:
data.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    2
Luggage.room      0
dtype: int64